#include "stdafx.h"
#include "behavier_Harvest_WorkMan.h"

BEHAVIER_HARVEST_WORKMAN::BEHAVIER_HARVEST_WORKMAN()
{
}

BEHAVIER_HARVEST_WORKMAN::~BEHAVIER_HARVEST_WORKMAN()
{
}

void BEHAVIER_HARVEST_WORKMAN::update(UNIT * pUnit)
{
}

void BEHAVIER_HARVEST_WORKMAN::end(UNIT * pUnit)
{
}
